<a href="https://colab.research.google.com/github/Amaliaaap/Tugas/blob/main/PreProcessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**1. Persiapan Data**

In [24]:
# Mengimport library yang digunakan (Pandas)
import pandas as pd

In [42]:
# membaca file CSV dan menyimpan datanya ke dalam sebuah DataFrame.
df = pd.read_csv('/content/drive/MyDrive/Data Mining/movie_sample_dataset.csv')
df.head()

,color,director_name,duration,gross,genres,movie_title,title_year,language,country,budget,imdb_score,actors,movie_facebook_likes
0,Color,Martin Scorsese,240,116866727.0,Biography|Comedy|Crime|Drama,The Wolf of Wall Street,2013,English,USA,100000000.0,8.2,"Leonardo DiCaprio,Matthew McConaughey,Jon Favreau",138000
1,Color,Shane Black,195,408992272.0,Action|Adventure|Sci-Fi,Iron Man 3,2013,English,USA,200000000.0,7.2,"Robert Downey Jr.,Jon Favreau,Don Cheadle",95000
2,color,Quentin Tarantino,187,54116191.0,Crime|Drama|Mystery|Thriller|Western,The Hateful Eight,2015,English,USA,44000000.0,7.9,"Craig Stark,Jennifer Jason Leigh,Zoë Bell",114000
3,Color,Kenneth Lonergan,186,46495.0,Drama,Margaret,2011,English,usa,14000000.0,6.5,"Matt Damon,Kieran Culkin,John Gallagher Jr.",0
4,Color,Peter Jackson,186,258355354.0,Adventure|Fantasy,The Hobbit: The Desolation of Smaug,2013,English,USA,225000000.0,7.9,"Aidan Turner,Adam Brown,James Nesbitt",83000

**2. Memeriksa Data**

In [26]:
# Menampilkan baris pertama dari dataset
df.head(1)

,color,director_name,duration,gross,genres,movie_title,title_year,language,country,budget,imdb_score,actors,movie_facebook_likes
0,Color,Martin Scorsese,240,116866727.0,Biography|Comedy|Crime|Drama,The Wolf of Wall Street,2013,English,USA,100000000.0,8.2,"Leonardo DiCaprio,Matthew McConaughey,Jon Favreau",138000

In [43]:
# Memeriksa informasi umum tentang dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99 entries, 0 to 98
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   color                 88 non-null     object
 1   director_name         88 non-null     object
 2   duration              99 non-null     int64
 3   gross                 91 non-null     float64
 4   genres                98 non-null     object
 5   movie_title           99 non-null     object
 6   title_year            99 non-null     int64
 7   language              99 non-null     object
 8   country               99 non-null     object
 9   budget                95 non-null     float64
 10  imdb_score            99 non-null     float64
 11  actors                99 non-null     object
 12  movie_facebook_likes  99 non-null     int64
dtypes: float64(3), int64(3), object(7)
memory usage: 10.2+ KB

In [44]:
import numpy as np

# Memeriksa jumlah missing value di setiap kolom
print(df.isnull().sum())

color                   11
director_name           11
duration                 0
gross                    8
genres                   1
movie_title              0
title_year               0
language                 0
country                  0
budget                   4
imdb_score               0
actors                   0
movie_facebook_likes     0
dtype: int64

**3. Membersihkan Data**

In [45]:
df.shape

(99, 13)

In [46]:
df.loc[:, 'color'] = df['color'].str.strip().str.capitalize()
df.loc[:, 'country'] = df['country'].str.strip().str.upper()
df = df[(df['duration']>=0)&
              (df['gross']>=0)&
              (df['title_year']>=0)&
              (df['budget']>=0)&
              (df['imdb_score']>=0)&
              (df['movie_facebook_likes']>=0)]
df = df.replace('N/A', pd.NA)
df.dropna(inplace=True)
df

,color,director_name,duration,gross,genres,movie_title,title_year,language,country,budget,imdb_score,actors,movie_facebook_likes
0,Color,Martin Scorsese,240,116866727.0,Biography|Comedy|Crime|Drama,The Wolf of Wall Street,2013,English,USA,100000000.0,8.2,"Leonardo DiCaprio,Matthew McConaughey,Jon Favreau",138000
1,Color,Shane Black,195,408992272.0,Action|Adventure|Sci-Fi,Iron Man 3,2013,English,USA,200000000.0,7.2,"Robert Downey Jr.,Jon Favreau,Don Cheadle",95000
2,Color,Quentin Tarantino,187,54116191.0,Crime|Drama|Mystery|Thriller|Western,The Hateful Eight,2015,English,USA,44000000.0,7.9,"Craig Stark,Jennifer Jason Leigh,Zoë Bell",114000
3,Color,Kenneth Lonergan,186,46495.0,Drama,Margaret,2011,English,USA,14000000.0,6.5,"Matt Damon,Kieran Culkin,John Gallagher Jr.",0
4,Color,Peter Jackson,186,258355354.0,Adventure|Fantasy,The Hobbit: The Desolation of Smaug,2013,English,USA,225000000.0,7.9,"Aidan Turner,Adam Brown,James Nesbitt",83000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
93,Color,Tony Gilroy,135,113165635.0,Action|Adventure|Thriller,The Bourne Legacy,2012,English,USA,125000000.0,6.7,"Jeremy Renner,Scott Glenn,Stacy Keach",31000
94,Color,Steve McQueen,134,56667870.0,Biography|Drama|History,12 Years a Slave,2013,English,USA,20000000.0,8.1,"Quvenzhané Wallis,Scoot McNairy,Taran Killam",83000
96,Color,Paul Greengrass,134,107100855.0,Biography|Drama|Thriller,Captain Phillips,2013,English,USA,55000000.0,7.9,"Tom Hanks,Chris Mulkey,Michael Chernus",65000
97,Color,David Ayer,134,85707116.0,Action|Drama|War,Fury,2014,English,USA,68000000.0,7.6,"Brad Pitt,Logan Lerman,Jim Parrack",82000
98,Color,Clint Eastwood,5,47034272.0,Biography|Drama|Music|Musical,Jersey Boys,2014,English,USA,40000000.0,6.9,"Johnny Cannizzaro,Steve Schirripa,Scott Vance",16000

In [47]:
# Mengecek apakah masih ada Missing data
print(df.isnull().sum())

color                   0
director_name           0
duration                0
gross                   0
genres                  0
movie_title             0
title_year              0
language                0
country                 0
budget                  0
imdb_score              0
actors                  0
movie_facebook_likes    0
dtype: int64

4. Transformasi Data

In [48]:
# Mengecek apa tipe data awal
df.dtypes

color                    object
director_name            object
duration                  int64
gross                   float64
genres                   object
movie_title              object
title_year                int64
language                 object
country                  object
budget                  float64
imdb_score              float64
actors                   object
movie_facebook_likes      int64
dtype: object

In [49]:
# Mengubah tipe data
df['gross'] = df['gross'].astype('int')
df['budget'] = df['budget'].astype('int')
df.dtypes

color                    object
director_name            object
duration                  int64
gross                     int64
genres                   object
movie_title              object
title_year                int64
language                 object
country                  object
budget                    int64
imdb_score              float64
actors                   object
movie_facebook_likes      int64
dtype: object

In [50]:
# Memisahkan kolom genre
print(df['genres'].head())

0            Biography|Comedy|Crime|Drama
1                 Action|Adventure|Sci-Fi
2    Crime|Drama|Mystery|Thriller|Western
3                                   Drama
4                       Adventure|Fantasy
Name: genres, dtype: object

In [52]:
# Memisahkan genre
genres_split = df['genres'].str.split('|', expand=True)
print(genres_split.head())

           0          1        2         3        4
0  Biography     Comedy    Crime     Drama     None
1     Action  Adventure   Sci-Fi      None     None
2      Crime      Drama  Mystery  Thriller  Western
3      Drama       None     None      None     None
4  Adventure    Fantasy     None      None     None

In [53]:
# Membuat kolom baru
genres_split.columns = [f'genre_{i+1}' for i in range(genres_split.shape[1])]

# Gabungkan dengan DataFrame asli
df = pd.concat([df, genres_split], axis=1)

Kita memberikan nama pada kolom baru dengan format genre_1, genre_2, dan seterusnya, berdasarkan jumlah kolom hasil pemisahan. Kita menggunakan pd.concat([df, genres_split], axis=1) untuk menggabungkan DataFrame asli dengan DataFrame genre yang baru dibuat secara horizontal.

In [54]:
df.drop(columns=['genres'], inplace=True)

# dengan df.drop(columns=['genres'], inplace=True), kita menghapus kolom 'genres' yang sudah tidak diperlukan lagi setelah pemisahan.

# tampilkan dataframe
df.head()

,color,director_name,duration,gross,movie_title,title_year,language,country,budget,imdb_score,actors,movie_facebook_likes,genre_1,genre_2,genre_3,genre_4,genre_5
0,Color,Martin Scorsese,240,116866727,The Wolf of Wall Street,2013,English,USA,100000000,8.2,"Leonardo DiCaprio,Matthew McConaughey,Jon Favreau",138000,Biography,Comedy,Crime,Drama,None
1,Color,Shane Black,195,408992272,Iron Man 3,2013,English,USA,200000000,7.2,"Robert Downey Jr.,Jon Favreau,Don Cheadle",95000,Action,Adventure,Sci-Fi,None,None
2,Color,Quentin Tarantino,187,54116191,The Hateful Eight,2015,English,USA,44000000,7.9,"Craig Stark,Jennifer Jason Leigh,Zoë Bell",114000,Crime,Drama,Mystery,Thriller,Western
3,Color,Kenneth Lonergan,186,46495,Margaret,2011,English,USA,14000000,6.5,"Matt Damon,Kieran Culkin,John Gallagher Jr.",0,Drama,None,None,None,None
4,Color,Peter Jackson,186,258355354,The Hobbit: The Desolation of Smaug,2013,English,USA,225000000,7.9,"Aidan Turner,Adam Brown,James Nesbitt",83000,Adventure,Fantasy,None,None,None

Kita memberikan nama pada kolom baru dengan format genre_1, genre_2, dan seterusnya, berdasarkan jumlah kolom hasil pemisahan. Kita menggunakan pd.concat([df, genres_split], axis=1) untuk menggabungkan DataFrame asli dengan DataFrame genre yang baru dibuat secara horizontal.

In [17]:
df.drop(columns=['genres'], inplace=True)

# dengan df.drop(columns=['genres'], inplace=True), kita menghapus kolom 'genres' yang sudah tidak diperlukan lagi setelah pemisahan.

# tampilkan dataframe
df.head()

,color,director_name,duration,gross,movie_title,title_year,language,country,budget,imdb_score,...,genre_1,genre_2,genre_3,genre_4,genre_5,genre_1,genre_2,genre_3,genre_4,genre_5
0,Color,Martin Scorsese,240,116866727.0,The Wolf of Wall Street,2013,English,USA,100000000.0,8.2,...,Biography,Comedy,Crime,Drama,None,Biography,Comedy,Crime,Drama,None
1,Color,Shane Black,195,408992272.0,Iron Man 3,2013,English,USA,200000000.0,7.2,...,Action,Adventure,Sci-Fi,None,None,Action,Adventure,Sci-Fi,None,None
2,color,Quentin Tarantino,187,54116191.0,The Hateful Eight,2015,English,USA,44000000.0,7.9,...,Crime,Drama,Mystery,Thriller,Western,Crime,Drama,Mystery,Thriller,Western
3,Color,Kenneth Lonergan,186,46495.0,Margaret,2011,English,usa,14000000.0,6.5,...,Drama,None,None,None,None,Drama,None,None,None,None
4,Color,Peter Jackson,186,258355354.0,The Hobbit: The Desolation of Smaug,2013,English,USA,225000000.0,7.9,...,Adventure,Fantasy,None,None,None,Adventure,Fantasy,None,None,None

5. Penyimpanan Data

In [55]:
df.to_csv('movie_dataset_cleaned.csv', index=False)